In [53]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

# FCI

In [54]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
import numpy as np

data  = pd.read_csv("Result\FCI.csv",header=None)
x = data.iloc[:,1:].to_numpy(copy=True).T
kmeans = KMeans(n_clusters=4, random_state=0)

result_min = []
result_max = []
for i in range(16):
    t = x[:,i].reshape(-1,1)
    kmeans.fit(t)
    label = kmeans.labels_
    x1 = t[np.where(label==0)[0].tolist(),:]
    x2 = t[np.where(label==1)[0].tolist(),:]
    x3 = t[np.where(label==2)[0].tolist(),:]
    x4 = t[np.where(label==3)[0].tolist(),:]
    label_min = [np.min(x1),np.min(x2),np.min(x3),np.min(x4)]
    label_min.sort()
    result_min.append(label_min)

result_min = np.array(result_min)

In [55]:
print(np.min(result_min,axis=0))
print(np.max(result_min,axis=0))
a = np.min(result_min,axis=0)[1:]
b = np.max(result_min,axis=0)[:-1]
print((a+b)/2)

[24.716 36.743 49.144 60.11 ]
[37.557 50.777 63.397 84.468]
[37.15   49.9605 61.7535]


# ERI

In [56]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
import numpy as np

data  = pd.read_csv("Result\ERI.csv",header=None)
x = data.iloc[:,1:].to_numpy(copy=True).T
kmeans = KMeans(n_clusters=4, random_state=0)

result_min = []
result_max = []
for i in range(16):
    t = x[:,i].reshape(-1,1)
    kmeans.fit(t)
    label = kmeans.labels_
    x1 = t[np.where(label==0)[0].tolist(),:]
    x2 = t[np.where(label==1)[0].tolist(),:]
    x3 = t[np.where(label==2)[0].tolist(),:]
    x4 = t[np.where(label==3)[0].tolist(),:]
    label_min = [np.min(x1),np.min(x2),np.min(x3),np.min(x4)]
    label_min.sort()
    result_min.append(label_min)

result_min = np.array(result_min)

In [57]:
print(np.min(result_min,axis=0))
print(np.max(result_min,axis=0))
a = np.min(result_min,axis=0)[1:]
b = np.max(result_min,axis=0)[:-1]
print((a+b)/2)

[ 0.404 19.072 34.351 68.223]
[28.963 53.542 72.925 94.936]
[24.0175 43.9465 70.574 ]


# ESI

In [58]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
import numpy as np

data  = pd.read_csv("Result\ESI.csv",header=None)
x = data.iloc[:,1:].to_numpy(copy=True).T
kmeans = KMeans(n_clusters=4, random_state=0)

result_min = []
result_max = []
for i in range(16):
    t = x[:,i].reshape(-1,1)
    kmeans.fit(t)
    label = kmeans.labels_
    x1 = t[np.where(label==0)[0].tolist(),:]
    x2 = t[np.where(label==1)[0].tolist(),:]
    x3 = t[np.where(label==2)[0].tolist(),:]
    x4 = t[np.where(label==3)[0].tolist(),:]
    label_min = [np.min(x1),np.min(x2),np.min(x3),np.min(x4)]
    label_min.sort()
    result_min.append(label_min)

result_min = np.array(result_min)

In [59]:
print(np.min(result_min,axis=0))
print(np.max(result_min,axis=0))
a = np.min(result_min,axis=0)[1:]
b = np.max(result_min,axis=0)[:-1]
print((a+b)/2)

[1.0000e-02 2.3966e+01 4.2216e+01 5.8143e+01]
[30.299 57.952 77.673 96.855]
[27.1325 50.084  67.908 ]


# SHI

In [60]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
import numpy as np

data  = pd.read_csv("Result\SHI.csv",header=None)
x = data.iloc[:,1:].to_numpy(copy=True).T
kmeans = KMeans(n_clusters=4, random_state=0)

result_min = []
result_max = []
for i in range(16):
    t = x[:,i].reshape(-1,1)
    kmeans.fit(t)
    label = kmeans.labels_
    x1 = t[np.where(label==0)[0].tolist(),:]
    x2 = t[np.where(label==1)[0].tolist(),:]
    x3 = t[np.where(label==2)[0].tolist(),:]
    x4 = t[np.where(label==3)[0].tolist(),:]
    label_min = [np.min(x1),np.min(x2),np.min(x3),np.min(x4)]
    label_min.sort()
    result_min.append(label_min)

result_min = np.array(result_min)

In [61]:
print(np.min(result_min,axis=0))
print(np.max(result_min,axis=0))
a = np.min(result_min,axis=0)[1:]
b = np.max(result_min,axis=0)[:-1]
print((a+b)/2)

[1.0000e-02 2.7641e+01 4.5592e+01 6.5493e+01]
[41.034 58.58  67.749 91.702]
[34.3375 52.086  66.621 ]


In [ ]:

[37.15   49.9605 61.7535]
[24.0175 43.9465 70.574 ]
[27.1325 50.084  67.908 ]
[34.3375 52.086  66.621 ]